@hostname = localhost
@port = 3333
@baseUrl = http://{{hostname}}:{{port}}
@version = v1

###
### Auth
###

### Register
POST {{baseUrl}}/api/{{version}}/auth/sign-up  HTTP/1.1
Content-Type: application/json

{
  "firstName": "Marek",
  "lastName": "Brandon",
  "email": "mb@gmail.com",
  "phone": "+421949000111",
  "sex": "male",
  "birthdate": "1996-08-28",
  "password": "hehe",
  "passwordConfirmation": "hehe"
}

### Sign in
# @name signIn
POST {{baseUrl}}/api/{{version}}/auth/sign-in  HTTP/1.1
Content-Type: application/json

{
  "email": "svoradov@gmail.com",
  "password": "hehe"
}

###
@token = {{signIn.response.body.$.token}}
@authToken = Bearer {{token}}

### Sign out
POST {{baseUrl}}/api/{{version}}/auth/sign-out  HTTP/1.1
Authorization: {{authToken}}

###
### Events
###

### Show events
GET {{baseUrl}}/api/{{version}}/events?page=1  HTTP/1.1
Authorization: {{authToken}}

### Store event
POST {{baseUrl}}/api/{{version}}/events  HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "title": "Winter fest 2022",
  "description": "Winter fest je umelecký festival na ktorom sa alternatíva, indie, elektronika, world music a punk stretávajú s klasikou; spolu s literatúrou, tancom, vizuálnym umením, filmom a divadlom.",
  "isPrivate": false,
  "location": "Stará Tržnica, Bratislava",
  "from": "2022-11-01T10:10",
  "to": "2022-11-02T20:20"
}

### Show event
GET {{baseUrl}}/api/{{version}}/events/1  HTTP/1.1
Authorization: {{authToken}}

### Update event
PUT {{baseUrl}}/api/{{version}}/events/1  HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "title": "Zimný Pohoda festival",
  "description": "Pohoda je umelecký festival na ktorom sa alternatíva, indie, elektronika, world music a punk stretávajú s klasikou; spolu s literatúrou, tancom, vizuálnym umením, filmom a divadlom.",
  "isPrivate": false,
  "location": "Letisko Piešťany",
  "from": "2022-11-01T10:04",
  "to": "2022-11-02T20:20"
}

### Delete events
DELETE  {{baseUrl}}/api/{{version}}/events/2  HTTP/1.1
Authorization: {{authToken}}

###
### Positions
###

### Show event positions
GET {{baseUrl}}/api/{{version}}/events/1/positions  HTTP/1.1
Authorization: {{authToken}}

### Store event position
POST {{baseUrl}}/api/{{version}}/events/6/positions  HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "title": "Čašníčka",
  "description": "Objednávanie a obsluhovanie hostí",
  "sexPreference": "none",
  "salary": 4.50,
  "maxEmployees": 12,
  "from": "2022-12-10T18:00",
  "to": "2022-12-11T03:00"
}

### Show event position
GET {{baseUrl}}/api/{{version}}/events/1/positions/1  HTTP/1.1
Authorization: {{authToken}}

### Update event position
PUT {{baseUrl}}/api/{{version}}/events/6/positions/10  HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "title": "Čašníčka",
  "description": "Objednávanie a obsluhovanie hostí",
  "sexPreference": "none",
  "salary": 4.50,
  "maxEmployees": 15,
  "from": "2022-12-10T18:00",
  "to": "2022-12-11T03:00"
}

### Delete event position
DELETE {{baseUrl}}/api/{{version}}/events/1/positions/1  HTTP/1.1
Authorization: {{authToken}}

###
### Employees
###

### Store employee
POST {{baseUrl}}/api/{{version}}/events/1/positions/1/employees  HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "userIds": [1]
}

### Delete employee
POST {{baseUrl}}/api/{{version}}/events/1/positions/1/employees/1  HTTP/1.1
Authorization: {{authToken}}
